### ISSUE TITLE
After deleted allure-results and re running project - allure opens an empty web page

### ISSUE THREAD

**Issue by saritanzu** [webdriverio/wdio-allure-reporter#92]
Hi, yesterday I manually deleted from my projects folders all of the allure-results files. I re-run my project several times but when I init allure it opens an empty browser page, there are no errors in the command line. I tried reinstalling it via brew command (I'm using mac) but it says that allure already install. 
What can I do? any ideas? Im stuck without a reported
*I deleted all the allure- results file because I wanted 'a clean start' of data since all the failures that it showed were part of testing the test cases
Using webdriverio, chai, JS and node

**Comment by BorisOsipov** [comment]
Hi @saritanzu 

1) Please check that new *.xml allure-results contain your tests run data - just check to get know that is not problem with report data.

2) We've ran into simular issue on mac. We got empty report due to some issues only on mac workstation. I don't have chance to investigate this issue cuz I don't have access to mac workstation.
Can you try generate report with your data in win\linux? will it work?

If there is no problem with report data it will be better to report your issue to https://github.com/allure-framework/allure2 project.

**Comment by saritanzu** [comment]
@BorisOsipov  Thanks for the fast reply.
1. I do not have any xml file in my allure-results folder. Can I generate one myself? If so, how should I name it?
2. If after restoring the xml file to the folder the issue remains I will do so.

**Comment by BorisOsipov** [comment]
> Can you try generate report with your data in win\linux? will it work?

P.S. If it is a problem with report generation ask in https://github.com/allure-framework/allure2 or on allure2 gitter.

**Comment by BorisOsipov** [comment]
@saritanzu have you resolved your issue?

**Comment by Prashi4peace** [comment]
Can you kindly tell us what need to be done to fix the problem... 
After deleted allure-results and re running project - allure opens an empty web page

Also getting below error
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

hoping reply
